### ISSUE TITLE
facet refining

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#100]
Updated for Aardvark Apr 2021:

For day to day record management, these fields ( in this order) are the most useful to keep as facets:
* Publication State
* Resource Class
* Provider
* Accrual Method
* Public/Restricted

The number of values for these fields is limited and they are easy-to-read.

--------------
The other fields on the main page could be removed entirely:
* Genre
* Place
* Year
* Subject
* Time Period
* Publisher
* Creator

These fields are descriptive and/or have many values. They are good for users searching for data, but less important for record management.

--------------
These fields are very important for record management, but don't work well as facets:
* Code
* Is Part Of
* Date Accessioned
* Date Retired

**Comment by karenmajewicz** [comment]
Could the "Limit Results By" functionality of the [Advanced Search](https://geo.btaa.org/advanced) page be utilized? This shows field names and a user can click in the box and select one or more values. This seems to be similar to the facets, but is much cleaner to use.

**Comment by karenmajewicz** [comment]
This issue is almost resolved. Adding Resource Class to the Main page is the only remaining facet that would be really helpful here.

**Comment by ewlarson** [comment]
<img width="306" alt="Screen Shot 2021-05-03 at 5 04 40 PM" src="https://user-images.githubusercontent.com/69827/116939284-b5e52380-ac31-11eb-8460-f6b88ba24fb4.png">
