### ISSUE TITLE
Publication State and Status fields

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#101]
Now that GEOMG uses a Publication State field, I don't think I need the custom "Status" field anymore. Any issues with deprecating it?

**Comment by ewlarson** [comment]
### TODO

Current steps to remove a field, ex. b1g_status_s:

* Write DB Migration to loop and remove field/value from all documents
* Remove from _document_fields.html.erb
* Remove from document_indexer.rb
* Remove from import_gblv1.rb
* Remove from document.rb - validations
* Remove from document.rb - attr_json
* Remove from import.rb
* Remove from import_btaa.rb
* Remove from document_indexer_test.rb
* Remove from document_test.rb
* Remove from import_gblv1_test.rb
* Remove from fixtures/documents.yml
* Remove from schema.json
* Remove from config/initializers/geomg/field_mappings_btaa.rb
* Remove from config/initializers/geomg/field_mappings_gblv1.rb

Also, what should happen to old document versions with the field and value present?
Probably best path here is to delete_all from the versions table, and start anew:
https://github.com/paper-trail-gem/paper_trail#3d-deleting-old-versions
