### ISSUE TITLE
Purpose of "Destroy" option in the Imports form

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#102]
This function does not "undo" the import, correct?  It is only for removing the log? Along with the CSV?  Should I delete old ones to conserve space?

**Comment by ewlarson** [comment]
Sorry for the confusion. That link is an artifact of using Rails' scaffolding to jump start the project. You really won't ever need to destroy (delete from the database) an import. I'll remove it from the page.

**Comment by karenmajewicz** [comment]
Not a problem having it there- I just wanted to make sure I understood its purpose.

**Comment by karenmajewicz** [comment]
I often need to repeat an import several times. Deleting failed attempts might be useful. In particular, some of the large CSV files that are faulty or duplicates don't need to be stored.

**Comment by ewlarson** [comment]
Just for the record... You can destroy/delete any Imports you want.

Destroying an Import will:

* Destroy all the associated ImportDocuments (think staging Documents, pre-imported)
* Destroy all the ImportMappings (the CSV to field mappings)
* And, it'll destroy the attached CSV file, too

However, it won't destroy any Documents that were successfully imported.
