### ISSUE TITLE
Import error message even though successful

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#103]
Every import (Solr template) I perform results in a Rails error page and this message to email:

> An ActionView::Template::Error occurred in imports#show:
> 
>   undefined method `metadata' for nil:NilClass
>   app/views/imports/_show_failed_tab.html.erb:31
> 

However, the imports are successful. Is this error related to the new tabbed layout on the imports page?

**Comment by ewlarson** [comment]
Let me reproduce. Seems like a simple issue.

**Comment by ewlarson** [comment]
Closing via https://github.com/BTAA-Geospatial-Data-Project/geomg/commit/34d7c30aefe7b7f294766b287936fb5c299c7ace
