### ISSUE TITLE
CSV import files rejected (size? error Status: 413)

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#104]
I am trying to make some updates to the records in the new hosted GEOMG. I believe that I am trying to upload CSV files that are too large. I keep receiving this error: 

> Error storing "my file name.csv". Status: 413

@mberkowski do you have a sense of how large of an import file the application can handle?  For context, I am working with collections with 1000s of rows. I have been splitting it up and trying smaller imports, but keep getting the error and wonder if there is a setting anywhere to indicate (or increase) this storage.

**Comment by mberkowski** [comment]
@karenmajewicz I'll look at this - rather than rejecting files by size it is probably rejecting all files and I need to fix a server directory. I'm going to grab an old csv and play with it.

**Comment by mberkowski** [comment]
@karenmajewicz Actually can you try another? I just took the prior Nebraska GIS csv and got it to load, this might have been due to an incompletely migrated set of files.

**Comment by karenmajewicz** [comment]
It's working now. Thanks.

**Comment by mberkowski** [comment]
Great. Some POST size defaults are much lower than we're used to and I have to configure for them. Never had to think about them before.
