### ISSUE TITLE
Aardvark - Collection records?

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geomg#113]
In B1G/GBLv1, we required a dc_format_s value for all documents, unless they were a "Collection" object.

```ruby
  # Required unless collection object
  validates :dct_format_s, presence: true, unless: :a_collection_object?

  def a_collection_object?
    dc_type_sm.include?('Collection')
  end
```

The `dc_type_sm` field is gone in Aardvark. How should we test for "Collection" objects in Aardvark?

**Comment by karenmajewicz** [comment]
dct_format_s is conditionally required only if there is a `http://schema.org/downloadUrl` key value pair in References. Could that be validated?

**Comment by karenmajewicz** [comment]
But, also, Collection objects can be tested using the new b1g_resourceClass_sm field.  One of the values is "Collection"

**Comment by ewlarson** [comment]
I'll work on the downloadUrl validation step.

Did you mean `gbl_resourceClass_sm` above? I don't see a b1g_resourceClass_sm field on the crosswalk I'm using:
https://github.com/BTAA-Geospatial-Data-Project/GBL-Schema-Update/blob/main/btaa_crosswalk_documentation.csv

**Comment by karenmajewicz** [comment]
Sorry, yes it's `gbl_resourceClass_sm`

**Comment by ewlarson** [comment]
Validating on the download key now:

```ruby
  # Test for collection and restricted
  validates :dct_format_s, presence: true, if: :a_downloadable_resource?

  # Downloadable Resouce
  def a_downloadable_resource?
    references_json.include?('downloadUrl')
  end
```
