### ISSUE TITLE
Autosuggest vocabulary for Resource Type

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#114]
Aerial photographs
Aerial views
Aeronautical charts
Armillary spheres
Astronautical charts
Astronomical models
Atlases
Bathymetric maps
Block diagrams
Bottle-charts
Cadastral maps
Cartographic materials
Cartographic materials for people with visual disabilities
Celestial charts
Celestial globes
Census data
Children's atlases
Children's maps
Comparative maps
Composite atlases
Digital elevation models
Digital maps
Early maps
Ephemerides
Ethnographic maps
Fire insurance maps
Flow maps
Gazetteers
Geological cross-sections
Geological maps
Globes
Gores (Maps)
Gravity anomaly maps
Index maps
LiDAR
Line data
Linguistic atlases
Loran charts
Manuscript maps
Mappae mundi
Mental maps
Mesh data
Meteorological charts
Military maps
Mine maps
Miniature maps
Multi-spectral data
Nautical charts
Outline maps
Photogrammetric maps
Photomaps
Physical maps
Pictorial maps
Plotting charts
Point cloud data
Point data
Polygon data
Portolan charts
Quadrangle maps
Raster data
Relief models
Remote-sensing maps
Road maps
Satellite imagery
Statistical maps
Stick charts
Strip maps
Table data
Thematic maps
Topographic maps
Tourist maps
Upside-down maps
Wall maps
World atlases
World maps
Worm's-eye views
Zoning maps

**Comment by ewlarson** [comment]
<img width="456" alt="Screen Shot 2021-05-03 at 5 23 46 PM" src="https://user-images.githubusercontent.com/69827/116940951-5dfbec00-ac34-11eb-9b15-643c5679e5fd.png">

**Comment by ewlarson** [comment]
Double checked. Is working for me here now... keeping this closed for now.

<img width="584" alt="Screen Shot 2021-05-05 at 11 12 40 AM" src="https://user-images.githubusercontent.com/69827/117174051-f6a87e00-ad92-11eb-888b-6e6b8eabbc16.png">
