### ISSUE TITLE
Update Rails to latest - remove mimemagic dependency

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geomg#125]
The old mimemagic dependency is keeping the aardvark branch from deploying. Will update Rails to remove mimemagic from the project.

**Comment by karenmajewicz** [comment]
Should we make an issue for this on GeoBlacklight too?

**Comment by ewlarson** [comment]
Nope, not needed. This is just a GEOMG issue, because of our file attachment feature.

**Comment by ewlarson** [comment]
Closing via 9f107db
