### ISSUE TITLE
Improve Advanced Search page

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#126]
The Limit Results section is very helpful and could be expanded to include these fields, which have limited values:

- [ ] Provider (already present; just change name
- [ ] Code (keep same)
- [ ] Member Of
- [ ] Is Part Of (keep same)
- [ ] Resource Class
- [ ] Resource Type
- [ ] Subject
- [ ] ISO Topic Category
- [ ] Format
- [ ] Suppressed
- [ ] Child Record
- [ ] Georeferenced
- [ ] Date Accessioned

**Comment by ewlarson** [comment]
Can certainly add all these facets. Two things to keep in mind:

1. They're gonna bloat the results from Solr, so pages might load a bit slower.

2. All these facets will appear on both our Advanced Search form and on the regular search results view. The order they appear in the catalog_controller.rb file also sets their order on the page. Do you want this facet order (as written above), given the regular result page will appear the same?

**Comment by ewlarson** [comment]
ACTUALLY! Found a work around. We can make the Advanced Search form facets be this long list and keep the regular results facet list shorter.

Order is still important though. Let me know about that.

**Comment by karenmajewicz** [comment]
I was just experimenting with the form to see how we enter values vs how the results shows up. If we have time, let's talk about it tomorrow when we meet. We might not need all these facets.
