### ISSUE TITLE
Add error report for manually created records with misconfigured bounding boxes

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#127]
I discovered that if I manually create a record, but enter an incorrect bounding box, it won't be imported into Solr. I will still be able to open it and update it in GEOMG, so it's not obvious right away why it doesn't show up. 

Is there a Solr error log record that could be displayed in these cases?

**Comment by ewlarson** [comment]
Best path forward here will be to enhance our bbox validation check.

**Comment by ewlarson** [comment]
Here's our bbox validation class: https://github.com/BTAA-Geospatial-Data-Project/geomg/blob/feature/locn-geometry-validator/app/models/document/locn_geometry_validator.rb

It _should_ prevent you from importing records or manually creating a record with a bad bbox. Maybe you have an example that can get past this check?

**Comment by ewlarson** [comment]
Closing. Reopen if necessary.
