### ISSUE TITLE
Date Range

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geomg#14]
- b1g_date_range_drsim
- maybe 2 boxes for user to fill in
- these are arranged [date1 TO date1] or [date1 TO date2]

**Comment by ewlarson** [comment]
Issue: "Collection" level objects, without a date_range specified, currently do not import into Solr.

To resolve:
1. Should we make up a range for everything 1 to 10000?
2. Should we make Traject/Solr less upset with missing range values?

**Comment by karenmajewicz** [comment]
Option 3. Geomg constructs it using one of the other date fields.

This field is a bit tedious to make by hand and duplicates the information in the other fields.  It seems like it would be best if the application makes it by parsing the Temporal field. If the Temporal field is empty or not parseable, we could use Date Issued or Solr Year.....

**Comment by karenmajewicz** [comment]
Having two boxes (from and to) would also be nice. Right now, we have 4 different date fields to fill in - several mimic each other. I am open to other strategies that could reduce duplicate labors.

**Comment by ewlarson** [comment]
Make "Date Range Start" and "Date Range End" fields.
