### ISSUE TITLE
Create Export packages for OpenGeoMetadata

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#163]

**Comment by karenmajewicz** [comment]
- [ ] Create documentation on how the JSONs should be organized
- [ ] Test current export crosswalk to ensure all of the fields are present
- [ ]

**Comment by karenmajewicz** [comment]
Here is my initial thoughts on how an export of JSONs could be accessed and organized:

- User selects a group of items as usual
- User chooses Export - any of the JSON options
- The resulting file is a ZIP with items structured in this kind of directory:
    - Provider
        - Resource Class (first value only)
            - full-id.json

**Comment by ewlarson** [comment]
How should we differentiate JSON formats here? 

Does this suffice?
* full-id.gblv1.json
* full-id.aardvark.json

**Comment by karenmajewicz** [comment]
New structure:
- Resource Class
  -  Code
     - id.json

**Comment by ewlarson** [comment]
Released in [v0.9.0](https://github.com/BTAA-Geospatial-Data-Project/geomg/releases/tag/0.9.0)
