### ISSUE TITLE
Cannot edit record VAC3073-M-00654

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#171]
None of the edits I do to this record using GEOMG or the spreadsheet import get applied. I am not sure what it is about this record - it does have a faulty thumbnail.

**Comment by ewlarson** [comment]
```
org.apache.solr.common.SolrException: ERROR: [doc=VAC3073-M-00654] Error adding field 'dct_publisher_sm'='[Indiana Department of Geology and Natural Resources, William B. Burford]' msg=Multiple values encountered for non multiValued copy field dc_publisher_sort: William B. Burford
```

Looks like we've got an Aardvark schema.xml bug. The schema includes a `<copyField source="dct_publisher_sm"     dest="dc_publisher_sort"/>` but you cannot sort on multivalued (string) fields.

We don't use a publisher sort in Geoportal or GEOMG, so removing this copyField and reindexing should help resolve a lot of the "gone missing" items from Solr.

**Comment by ewlarson** [comment]
Reindexes properly with Solr schema.xml file change in place: https://github.com/BTAA-Geospatial-Data-Project/geoportal-solr-config/releases/tag/4.1.1
