### ISSUE TITLE
GeoDev Has Version ... Browse All not working

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#176]
See this link https://geodev.btaa.org/catalog/27001-address-points

and click on Browse all at the bottom

**Comment by ewlarson** [comment]
Browsing the Wabash Topo items is broken in production, too:
https://geo.btaa.org/catalog/88cc9b19-3294-4da9-9edd-775c81fb1c59

Investigating...
