### ISSUE TITLE
Can only export one page of results or everything in the database

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#179]
### What should happen:

1. Refine a set of results using search/facets
2. Select everything on the page
3. Click "All results on this page are selected. Select all results that match this search."
4. Export to CSV
5. **CSV contains only the selected items**

### What is currently happening:

1. Refine a set of results using search/facets
2. Select everything on the page
3. Click "All results on this page are selected. Select all results that match this search."
4. Export to CSV
5. **CSV contains all items in the database**
---
Workaround in the meantime: 

- When I select just the items on one page at a time, the CSV exports correctly. 
- I can adjust how many items are on one page by manually changing the URL query part `&rows=`. This will export correctly. 
- It is just the "Select all results that match this search" that fails.

**Comment by ewlarson** [comment]
Gah! That's not fun, but I just ran a couple of ~200 item CSV exports after faceting.

Can you copy/paste the URL for the search result set you are trying to export? -- maybe we're missing a facet in the new API Ids Controller that needs to scope the export.

**Comment by karenmajewicz** [comment]
Hmm, can't reproduce now. On Friday, I was trying to export just items with the Resource Type "Websites" and got everything four times in a row. But, it is working now. I will try a few different queries to see if I can figure out what happened.

**Comment by karenmajewicz** [comment]
Aha - reproduced the issue. It was when I used the Advanced Search to find items within a Code. Here is an example: https://geomg.lib.umn.edu/documents?q=&f%5Bb1g_code_s%5D%5B%5D=03b-19113

Oddly, this returned all >50,000 results, but the CSV was listed a N/A

![Screen Shot 2021-12-13 at 3 57 41 PM](https://user-images.githubusercontent.com/2367677/145895574-4c8ab4cf-9d05-496b-baf9-ffd1b94bc455.png)

**Comment by karenmajewicz** [comment]
Getting the same problem with using the Advanced Search for the Is Member Of field: https://geomg.lib.umn.edu/documents?q=&f%5Bpcdm_memberOf_sm%5D%5B%5D=a-b-d-local-government-open-data

So, maybe some of these are not in the controller or the Advanced Search is adding something to the query?

![Screen Shot 2021-12-13 at 4 02 51 PM](https://user-images.githubusercontent.com/2367677/145896153-12ea901e-877b-494a-a177-09aeaedd67bb.png)

**Comment by ewlarson** [comment]
Nice! Well... I'm glad you could reproduce it 😄 . I think I know the error. I'll try and find a little time this week to troubleshoot.

**Comment by karenmajewicz** [comment]
Thanks! I can definitely still work with the bug in effect, so no hurry.

**Comment by karenmajewicz** [comment]
Seeing a limitation today of increasing a single page's result set size: I manually created a single page with 980 items in order to export.  (https://geomg.lib.umn.edu/documents?f%5Bb1g_dct_accrualMethod_s%5D%5B%5D=CKAN&f%5Bgbl_resourceClass_sm%5D%5B%5D=Datasets&rows=1000&sort=score%2Bdesc%252C%2Bdc_title_sort%2Basc)

The page appears fine. However, when attempting to export the set to a CSV, the app errored out with the message `414 Request-URI Too Large`

I could make a different issue for this, but I am not sure that it is actually problem that needs fixing. (fixing the multiple-pages export method is probably better).

**Comment by karenmajewicz** [comment]
This is occurring again today.
