### ISSUE TITLE
Aardvark: add new spatial fields

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geomg#190]
Requires Solr schema update.

* dcat_bbox
* dcat_centroid (replaces dcat_centroid_ss)

**Comment by karenmajewicz** [comment]
Q. Do we have a path for using locn_geometry for complex or multiple geometries in Geomg?

**Comment by ewlarson** [comment]
No, not yet. As currently written our locn_geometry validations would likely reject anything that wasn't a simple bbox.

**Comment by karenmajewicz** [comment]
I'll make a separate issue for that and we can look at it later this year. (Maybe Q3)
