### ISSUE TITLE
Develop order for facets

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#22]
These 3 fields at the top would be the most useful:

1. Genre
2. Contributor 
3. Type

After that, the remaining facets could appear beneath in the same order as our GeoBlacklight.

**Comment by ewlarson** [comment]
Maybe style these to separate them from the other facets, to avoid confusion switching between public and admin interfaces

**Comment by karenmajewicz** [comment]
Now that there is a CSV download available, I am realizing that different facets would be more useful in selecting items. So, after the first 3 (Genre, Contributor, and Type), these could come next:

Code
Is Part Of
Date Accessioned
Date Retired
Public/Restricted

The remaining fields (Subject, Year, Time Period, Publisher, Creator, etc. ) would be used much less frequently to find items, but might be handy. It appears that I could manually create a search string if needed.
