### ISSUE TITLE
Centroid: Autopopulate

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#28]
The Centroid field should autopopulate based upon the Bounding Box

**Comment by ewlarson** [comment]
JS trigger/function to auto-populate this value. Sanity test the Bounding Box value, too.

**Comment by karenmajewicz** [comment]
And round centroids to 4 decimal places.

**Comment by karenmajewicz** [comment]
This appears to be functioning.
