### ISSUE TITLE
Exception Notification

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geomg#47]
Add some app-level exception handling/capturing and notification.

**Comment by karenmajewicz** [comment]
Related to this - when manually creating a record, if the application has an error upon trying to save it, the previously entered information is lost.

**Comment by ewlarson** [comment]
Do you have an example identifier? Imports shouldn't lose data, the old version will still be in the system.

**Comment by karenmajewicz** [comment]
The title of the item was "Kingsbury's Atlas of Indiana." I tried using the form to create a new record. I must have left something out, because when I clicked the Create Document button, I got an error page. When I used the browser to return to the page, all of the entries were cleared.
