### ISSUE TITLE
Bbox - import and persist in W,S,E,N 

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geomg#50]
Currently, we import and export CSV in W,S,E,N syntax, but we save the data in the database as solr-syntax ENVELOPE(....). This makes editing or creating new documents awkward.

Let's just have data talk W,S,E,N and transform those values to solr syntax for indexing.

**Comment by ewlarson** [comment]
ImportBtaa supports this in [feature/aardvark](https://github.com/BTAA-Geospatial-Data-Project/geomg/tree/feature/aardvark)

**Comment by karenmajewicz** [comment]
This appears to be functioning with the latest import/exports
