### ISSUE TITLE
Bug displaying records on 1st two pages of full results list

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#62]
The first page of records only is displaying 5 records. The second page is displaying 0 records.  This may or may not be related to the first 2 records, which seem to be malformed and throw an error when I try to export them.

**Comment by ewlarson** [comment]
Can you send me a link to reproduce? Thanks!

**Comment by karenmajewicz** [comment]
I forgot to include screenshots. It happens from the main page of the OIT hosted GEOMG (https://lib-geomg-dev-01.oit.umn.edu/)
![Screen Shot 2020-10-06 at 1 30 11 PM](https://user-images.githubusercontent.com/2367677/95251096-a8bd9e80-07e0-11eb-9d95-fc831dced220.png)
![Screen Shot 2020-10-06 at 1 29 56 PM](https://user-images.githubusercontent.com/2367677/95251102-a9563500-07e0-11eb-90ff-db3a99d83fd4.png)

**Comment by karenmajewicz** [comment]
I am thinking of deleting the first 3 records, but wanted to document the error before doing so.
