### ISSUE TITLE
CSV - Field Mappings BTAA - Missing fields

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geomg#68]
Looks like two b1g_* fields are still missing from our [BTAA CSV field mapping](https://github.com/BTAA-Geospatial-Data-Project/geomg/blob/develop/config/initializers/geomg/field_mappings_btaa.rb)

* b1g_geonames_sm
* b1g_dateRetired_s

@karenmajewicz // We'll likely need these two fields for complete round-tripping of data in and out of GEOMG. Any reason not to add and implement them?

**Comment by karenmajewicz** [comment]
That's an oversight - we should probably add these.

**Comment by karenmajewicz** [comment]
'Retired': {
        destination: 'b1g_retired_s',
        delimited: false,
        transformation_method: nil
      },
      'Geonames': {
        destination: 'b1g_geonames_sm',
        delimited: true,
        transformation_method: nil
      }

**Comment by ewlarson** [comment]
How about 'Date Retired' (since it should be a date) and it corresponds with 'Date Accessioned'?

**Comment by karenmajewicz** [comment]
Sure - **Date Retired** is more clear

**Comment by ewlarson** [comment]
'Date Retired': {
        destination: 'b1g_dateRetired_s',
        delimited: false,
        transformation_method: nil
      },

**Comment by ewlarson** [comment]
Done! https://github.com/BTAA-Geospatial-Data-Project/geomg/commit/9eeac476aac050d158de24a9f6270c398036063e
