### ISSUE TITLE
Batch Updates - Determine method for setting Publication State in batches

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#70]
Imported items automatically are set to Draft and I don't see a way to set them to published except one by one. Options:

1. Add this field to the Import template
2. Allow a user to select items within the interface and batch set them to Published.

**Comment by ewlarson** [comment]
Shipped with BulkActions https://github.com/BTAA-Geospatial-Data-Project/geomg/commit/2938c1ad0248ee015ca16d7dd46960dc8e277a19
