### ISSUE TITLE
Report which rows do not import

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#71]
When importing a CSV, sometimes a few don't import. For example, the total rows may be 74, but only 71 are imported. Which rows were rejected?

**Comment by ewlarson** [comment]
Sure. Can you share a file where this happens?

**Comment by karenmajewicz** [comment]
[This is the spreadsheet I am working with.](https://docs.google.com/spreadsheets/d/1RVHi8ek2OqcgFgmNlGDA1QwXAWYsyvpAbj2dlb4nVMQ/edit?usp=sharing)

Here is what I tried last week:
1. Uploaded 74 records from the "sample" tab. Only 71 imported.
2. Guessed at which fields were causing the problems and tried to re-upload a few times. Still, only 71 imported.
3. I figured out which 3 didn't work and removed them from the sample tab over to the "troubleshoot" tab.
4. Uploaded 71 records from the "sample" tab. Only 69 imported.

At that point, I stopped, because I think I need more error reporting to know how to fix items.

**Comment by ewlarson** [comment]
Error on the 71 sample records: Encoding::UndefinedConversionError ("\xC3" from ASCII-8BIT to UTF-8)

So it appears there are some character encoding issues with the file contents. "Forcing" the file to UTF-8 makes the import succeed.

**Comment by karenmajewicz** [comment]
That makes sense. Should we add a `force_encoding` command to the import code?

I re-saved my CSV as UTF-8, and re-uploaded, but got the same error. Not sure how to troubleshoot where the specific character issues are - perhaps in the URLs.

**Comment by ewlarson** [comment]
Yes, I'm going to use `force_encoding` to read the CSV as UTF-8. Been trying to import your big records.csv sheet, just to see if any additional errors pop up... 21K records into the import... will let you know.

**Comment by ewlarson** [comment]
Force-encoding: https://github.com/BTAA-Geospatial-Data-Project/geomg/commit/30eaa8e9ff2c78dc05528b54c44a8fe52d8b8863

**Comment by ewlarson** [comment]
Closing as force encoding resolves the original error here. Background job processing should also better trap individual import errors, and will capture import document state.
