### ISSUE TITLE
Import - GBL SolrDocuments

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geomg#85]

**Comment by ewlarson** [comment]
http://localhost:8983/solr/geoportal-core-development/select?q=*%3A*&rows=100&wt=csv&csv.mv.separator=|

Set multivalue separator to pipe.

**Comment by ewlarson** [comment]
Provisionally complete; needs some review and discussion.

**Comment by ewlarson** [comment]
See: https://github.com/BTAA-Geospatial-Data-Project/geomg/wiki/Solr---CSV-Import-Mappings

**Comment by karenmajewicz** [comment]
Testing out an import of 38 items. A few import successfully, then the following error is applied to the rest:

`failed Error - #<Traject::SolrJsonWriter::MaxSkippedRecordsExceeded: Traject::SolrJsonWriter: Exceeded maximum number of skipped records (0): aborting: execution expired>`

**Comment by ewlarson** [comment]
Ahhhh... passed validation, got rejected by Solr. Can you send me the CSV you are importing?
