### ISSUE TITLE
Retain form edits when using sidebar navigation

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#90]
I tried this on two browsers and got the same issue:

Current behavior:
1. Open the form editor to create a new record OR open an existing record
2. add or edit the Title
3. Use the navigation to jump down to another section, such as Links
4. Scroll back up to Title - entered information is gone

It is as if the browser is refreshing the page when clicking to a new anchor. If the user has not pressed the update document button yet, the entered info is lost.

**Comment by ewlarson** [comment]
This stimulus controller appears to be a nice fix:
https://stimulus-components.netlify.app/docs/components/stimulus-scroll-to/
