### ISSUE TITLE
Clarify import error: "ActiveRecord::RecordInvalid: Validation failed: Reference is invalid"

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#92]
What is being checked here?

**Comment by ewlarson** [comment]
Likely a bad dct_references val.

**Comment by karenmajewicz** [comment]
Find examples

**Comment by karenmajewicz** [comment]
imports/113 was a test import of all of the Solr docs. There are numerous reference errors in this batch.

The first record (64b7b23699a04043abdf3b648d742842_4) shows this type of error. Here is the item in the Prod Geoportal: https://geo.btaa.org/catalog/64b7b23699a04043abdf3b648d742842_4/admin

Here is the value in the dct_references field:
`{"http://schema.org/url":"https://public-iowadot.opendata.arcgis.com/datasets/64b7b23699a04043abdf3b648d742842_4","https://schema.org/downloadUrl":"https://public-iowadot.opendata.arcgis.com/datasets/64b7b23699a04043abdf3b648d742842_4.zip","urn:x-esri:serviceType:ArcGIS#FeatureLayer":"https://gis.iowadot.gov/public/rest/services/Pavement_Management/Pavement_Raw_Data/FeatureServer/4"}`

**Comment by karenmajewicz** [comment]
All of the records that were rejected are of the status "Retired."  I put together a [CSV of 7 records](https://docs.google.com/spreadsheets/d/1hs99GuG8d3hw4X582TGxldhDy0eZrHgaGSGhd2Zg0Lg/edit?usp=sharing) that were rejected.  

I tested this set of 7 and they still error out.

**Comment by ewlarson** [comment]
Troubleshooting these docs here... looks like we've got a nil category value in the references after the CSV to Document transformation. Look way down here at the bottom...

```ruby
=> [#<ImportDocument:0x00007fba03164558
  id: 1397,
  friendlier_id: "64b7b23699a04043abdf3b648d742842_4",
  title: "Pavement Data: Iowa, 2013",
  json_attributes:
   {"b1g_code_s"=>"03a-02",
    "dct_isPartOf_sm"=>"",
    "b1g_status_s"=>"Active",
    "suppressed_b"=>"TRUE",
    "dc_subject_sm"=>["Transportation"],
    "b1g_dateAccessioned_s"=>"2019-09-04",
    "dc_format_s"=>"Shapefile",
    "solr_geom"=>"ENVELOPE(-95.83,-90.16,42.65,40.39)",
    "b1g_keyword_sm"=>
     ["Iowa",
      "IDOT",
      "RAW",
      "Pavement Management",
      "Pavement Condition",
      "IRI",
      "Rutting",
      "Faulting",
      "Cracking",
      "PCI",
      "Pavement Distress",
      "Asset",
      "Classification"],
    "layer_geom_type_s"=>"Vector",
    "dct_provenance_s"=>"University of Iowa",
    "dct_accrualMethod_s"=>"ArcGIS Hub",
    "b1g_image_ss"=>nil,
    "dct_issued_s"=>"2016-07-28",
    "dc_description_s"=>
     "RAW Pavement Management Information System data collection points. Pavement distress data collected on Iowa Primary and Interstate routes. The data is collected by a 3rd party vendor using forward and downward facing imagery. Data fields are subject to change in future REST services. Raw data collection points are only visible inside county wide scale.",
    "dc_identifier_s"=>"https://hub.arcgis.com/datasets/64b7b23699a04043abdf3b648d742842_4",
    "dct_accessRights_sm"=>"",
    "dct_temporal_sm"=>["2013"],
    "b1g_date_range_drsim"=>"2013-2013",
    "solr_year_i"=>"2013",
    "dc_rights_s"=>"Public",
    "dct_alternativeTitle_sm"=>["2013"],
    "dc_language_sm"=>["English"],
    "dc_title_s"=>"Pavement Data: Iowa, 2013",
    "dct_references_s"=>
     [{"value"=>"https://public-iowadot.opendata.arcgis.com/datasets/64b7b23699a04043abdf3b648d742842_4", "category"=>"documentation_external"},
      {"value"=>"https://public-iowadot.opendata.arcgis.com/datasets/64b7b23699a04043abdf3b648d742842_4.zip", "category"=>nil},
      {"value"=>"https://gis.iowadot.gov/public/rest/services/Pavement_Management/Pavement_Raw_Data/FeatureServer/4", "category"=>"arcgis_feature_layer"}],
```

Oh! This looks like the GEOMG importing supports "http://schema.org/downloadUrl", but not "https://schema.org/downloadUrl".

What is correct? Shouldn't these all be non-secure? -- all the rest of our reference URIs are not secure.

**Comment by karenmajewicz** [comment]
Ah, thank you. The https must be it. I will fix and re-check.

**Comment by ewlarson** [comment]
Looks like we've been a bit inconsistent with http vs. https here:
https://github.com/BTAA-Geospatial-Data-Project/geomg/blob/develop/app/models/document/reference.rb

I'm wondering two things:

1) Should we make it all uniformly non-secure?
2) Or should we work to have the application respect both protocols?

Does GBL have any opinions here?

**Comment by ewlarson** [comment]
Closing via https://github.com/BTAA-Geospatial-Data-Project/geomg/commit/62e0edd1ef0ff9527ac9d28665353adacdfe5d5c
