### ISSUE TITLE
CSV export maxes out at 10,005 records

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#93]
Not sure about the feasibility or necessity for increasing this, but something to note. This makes it tricky to export the full collection to make batch changes as there is not a great way to parse the remaining records.

**Comment by karenmajewicz** [comment]
I just checked this again and it maxed out at 9997 records this time.

**Comment by ewlarson** [comment]
Related: https://github.com/BTAA-Geospatial-Data-Project/geomg/issues/130

**Comment by ewlarson** [comment]
Looking into Solr's cursorMark feature:
https://solr.apache.org/guide/6_6/pagination-of-results.html#fetching-a-large-number-of-sorted-results-cursors

**Comment by karenmajewicz** [comment]
Finding this to be a problem again. Large exports over about 10,000 records don't seem to process and never show up in the Notifications section.

**Comment by ewlarson** [comment]
Running large batch exports locally it appears we're just running into Net HTTP timeouts for long running queries that crawl Solr while building the export file.

Going to refactor our export process to use an optimized controller with better per_page limits and limited metadata in results to see if we can improve overall performance here. My initial refactor attempt here is looking promising.

**Comment by karenmajewicz** [comment]
This is working now.
